Vagrant.configure('2') do |config|
  config.vm.hostname = 'docklet-001'
  # Alternatively, use provider.name below to set the Droplet name. config.vm.hostname takes precedence.

  config.vm.provider :digital_ocean do |provider, override|
    override.ssh.private_key_path = '~/.ssh/id_rsa'
    override.vm.box = 'docklet'
    provider.token = 'c1718b03f9f93867b608bc1e21fac1365f2b2b7b149a000692b5d1564bfb5a19'
    provider.image = 'ubuntu-16-04-x64'
    provider.region = 'nyc3'
    provider.size = '512mb'
  end
end
